// ==========================================================
// PROTOCOL_DB — Base de conocimiento clínico teledermatología
// Fuente: PROTOCOLOS TD 2023
// Generado: 2026-03-09
// PARTE 1 de 2 (registros 1–15)
// ==========================================================

const PROTOCOL_DB_VERSION = "TD2023-v1.0";

const PROTOCOL_DB = [
    {
        id: 1,
        diagnosis: "ACNE INFLAMATORIO LEVE",
        diagnosis_short: "Acné inflamatorio leve",
        triage_seed: "GREEN",
        tags: ["acne", "inflamatorio", "leve", "rostro", "adapaleno", "seborrea", "comedones"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ACNE INFLAMATORIO LEVE",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: NO APRETAR LESIONES, NO CONSUMIR EN EXCESO LÁCTEOS Y SUS DERIVADOS, NO DEJAR EL PELO EN ROSTRO, ENTRE OTROS. 2.- PROTECCION SOLAR EN GEL O FLUIDO SPF 30 ó 50 MAÑANA Y MEDIO DÍA Y CADA 2 HORAS SI ESTÁS AL SOL. 3.- ASEO JABONOSO EN ROSTRO MAÑANA Y NOCHE CON JABONES QUE TIENDAN A DISMINUIR LA SEBORREA FACIAL. 4.- ADAPALENO 0,1% GEL O CREMA, APLICAR EN LA NOCHE O ADAPALENO 0.3% NOCHE POR MEDIO EN ZONAS DE ACNÉ DEL ROSTRO UNA CAPA FINA, EVITANDO LOS PÁRPADOS, COMENZAR NOCHE POR MEDIO Y SEGÚN TOLERANCIA IR AUMENTANDO LA FRECUENCIA, SI IRRITA ESPACIAR A CADA 2 NOCHES (MEDICAMENTO DE CANASTA APS). 5.- CONTROL X TELEDERMATOLOGIA EN 3 MESES.",
        education_text: "EXPLICAR LA IMPORTANCIA DEL AUTOCUIDADO CON LAS MEDIDAS GENERALES Y LA CONSTANCIA EN EL TRATAMIENTO. MENCIONAR QUE NO SE TIENE LA CURA PARA EL ACNÉ, PERO SI ES RIGUROSO EN EL TRATAMIENTO, PODEMOS MEJORAR SUS LESIONES.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 2,
        diagnosis: "ACNE INFLAMATORIO MODERADO",
        diagnosis_short: "Acné inflamatorio moderado",
        triage_seed: "YELLOW",
        tags: ["acne", "inflamatorio", "moderado", "rostro", "adapaleno", "doxiciclina", "antibiotico oral", "seborrea"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ACNE INFLAMATORIO MODERADO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: NO APRETAR LESIONES, NO CONSUMIR EN EXCESO LÁCTEOS Y SUS DERIVADOS, NO DEJAR EL PELO EN ROSTRO, ENTRE OTROS. 2.- PROTECCION SOLAR EN GEL O FLUIDO SPF 30 ó 50 MAÑANA Y MEDIO DÍA. 3.- ASEO JABONOSO EN ROSTRO MAÑANA Y NOCHE CON JABONES QUE TIENDAN A DISMINUIR LA SEBORREA FACIAL. 4.- ADAPALENO 0,1% GEL O CREMA, APLICAR EN LA NOCHE O ADAPALENO 0.3% NOCHE POR MEDIO EN ZONAS DE ACNÉ DEL ROSTRO UNA CAPA FINA, EVITANDO LOS PÁRPADOS, COMENZAR NOCHE POR MEDIO Y SEGÚN TOLERANCIA IR AUMENTANDO LA FRECUENCIA, SI IRRITA ESPACIAR A CADA 2 NOCHES (MEDICAMENTO DE CANASTA APS). 5.- DOXICICLINA COMP 100MG, 1 COMP EN LAS NOCHES DESPUÉS DE LAS COMIDAS POR 6 SEMANAS, SIN LECHE (MEDICAMENTO DE CANASTA APS). 6.- CONTROL X TELEDERMATOLOGIA EN 3 MESES.",
        education_text: "EXPLICAR QUE EL ACNÉ ES UNA PATOLOGÍA QUE AFECTA LA PIEL Y OCURRE CUANDO LA UNIDAD FOLICULOPILOSEBÁCEA SE OBSTRUYE POR HIPERQUERATOSIS FOLICULAR, AUMENTO DE SEBORREA, PROLIFERACIÓN BACTERIANA E INFLAMACIÓN. ESTO OCURRE DE PREFERENCIA EN LA ADOLESCENCIA CON UN TIEMPO DE DURACIÓN VARIABLE Y AFECTA EL ROSTRO, PECHO Y ESPALDA HABITUALMENTE. ES MUY IMPORTANTE RECALCAR EL AUTOCUIDADO CON LAS MEDIDAS GENERALES Y LA CONSTANCIA EN EL TRATAMIENTO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 3,
        diagnosis: "ACNE INFLAMATORIO SEVERO",
        diagnosis_short: "Acné inflamatorio severo",
        triage_seed: "RED",
        tags: ["acne", "inflamatorio", "severo", "rostro", "isotretinoina", "derivar", "control presencial", "doxiciclina"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ACNE INFLAMATORIO SEVERO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: NO APRETAR LESIONES, NO CONSUMIR EN EXCESO LÁCTEOS Y SUS DERIVADOS, NO DEJAR EL PELO EN ROSTRO, ENTRE OTROS. 2.- PROTECCION SOLAR EN GEL O FLUIDO SPF 30 ó 50 MAÑANA Y MEDIO DÍA. 3.- ASEO JABONOSO EN ROSTRO MAÑANA Y NOCHE. 4.- ADAPALENO 0,1% GEL O CREMA, APLICAR EN LA NOCHE EN ROSTRO UNA CAPA FINA, EVITANDO LOS PÁRPADOS, COMENZAR NOCHE POR MEDIO Y SEGÚN TOLERANCIA IR AUMENTANDO LA FRECUENCIA (MEDICAMENTO DE CANASTA APS). 5.- DOXICICLINA COMP 100MG, 1 COMP EN LAS NOCHES DESPUÉS DE LAS COMIDAS POR 6 SEMANAS, SIN LECHE (MEDICAMENTO DE CANASTA APS). 6.- CONTROL PRESENCIAL PUES REQUIERE USO DE ISOTRETINOINA ORAL. DERIVAR CON HEMOGRAMA, PERFIL HEPÁTICO Y PERFIL LIPÍDICO.",
        education_text: "EXPLICAR LA IMPORTANCIA DEL AUTOCUIDADO CON LAS MEDIDAS GENERALES Y LA CONSTANCIA EN EL TRATAMIENTO. MENCIONAR QUE NO SE TIENE LA CURA PARA EL ACNÉ, PERO SI ES RIGUROSO EN EL TRATAMIENTO, PODEMOS MEJORAR SUS LESIONES. EN SU CASO EL GRADO DE ACNÉ NECESITA CONTROL PRESENCIAL Y USO DE ISOTRETINOINA ORAL.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 4,
        diagnosis: "ACNE COMEDONIANO",
        diagnosis_short: "Acné comedoniano",
        triage_seed: "GREEN",
        tags: ["acne", "comedoniano", "comedones", "rostro", "adapaleno", "seborrea"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ACNE COMEDONIANO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: NO APRETAR LESIONES, NO CONSUMIR EN EXCESO LÁCTEOS Y SUS DERIVADOS, NO DEJAR EL PELO EN ROSTRO, ENTRE OTROS. 2.- PROTECCION SOLAR EN GEL O FLUIDO SPF 30 ó 50 MAÑANA Y MEDIO DÍA. 3.- ASEO JABONOSO EN ROSTRO MAÑANA Y NOCHE CON JABONES QUE TIENDAN A DISMINUIR LA SEBORREA FACIAL. 4.- ADAPALENO 0,1% GEL O CREMA, APLICAR EN LA NOCHE O ADAPALENO 0.3% NOCHE POR MEDIO EN ZONAS DE ACNÉ DEL ROSTRO UNA CAPA FINA, EVITANDO LOS PÁRPADOS, COMENZAR SOLO 2 NOCHES A LA SEMANA Y LUEGO SI LO TOLERA NOCHE POR MEDIO (MEDICAMENTO DE CANASTA APS). 5.- CONTROL X TELEDERMATOLOGIA EN 3 MESES.",
        education_text: "EXPLICAR QUE EL ACNÉ ES UNA PATOLOGÍA QUE AFECTA LA PIEL Y OCURRE CUANDO LA UNIDAD FOLICULOPILOSEBÁCEA SE OBSTRUYE POR HIPERQUERATOSIS FOLICULAR, AUMENTO DE SEBORREA, PROLIFERACIÓN BACTERIANA E INFLAMACIÓN. ES MUY IMPORTANTE RECALCAR EL AUTOCUIDADO CON LAS MEDIDAS GENERALES Y LA CONSTANCIA EN EL TRATAMIENTO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 5,
        diagnosis: "DERMATITIS ATOPICA",
        diagnosis_short: "Dermatitis atópica",
        triage_seed: "GREEN",
        tags: ["dermatitis", "atopica", "prurito", "eczema", "pediatrico", "hidrocortisona", "humectacion", "cronico"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- DERMATITIS ATOPICA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: BAÑOS CORTOS MENOS DE 3 MINUTOS, POCO JABÓN (SOLO AXILAS, GENITALES POR FUERA Y PIES) Y CHAMPÚ SOLO EN EL PELO QUE NO ESCURRA POR EL CUERPO, LUBRICACIÓN DIARIA, ENJUAGAR ROPA 2 VECES, NO USAR SUAVIZANTES PARA LA ROPA, USAR ROPA DE ALGODÓN Y EVITAR LANA, NO USAR PERFUMES NI PINTURAS, NO RASCARSE, NO SOBRE ABRIGAR. 2.- HIDROCORTISONA CREMA 1% APLICAR 2 VECES AL DÍA X 7 DÍAS EN LESIONES. 3.- LUBRICAR CON CREMA HUMECTANTE DE CANASTA; SINO TIENE PUEDE USAR NIVEA TAPA AZUL, LUBRIDERM, PIELARMINA O VASELINA SÓLIDA. 4.- HIDROXICINA JARABE SEGÚN KILOS DE PESO EN LA NOCHE X 1 MES (SINO HAY HIDROXICINA SE PUEDE REEMPLAZAR POR CLORFENAMINA JARABE). 5.- CONTROL POR TELEDERMATOLOGIA 1 MES.",
        education_text: "EXPLICAR QUE LA DERMATITIS ATÓPICA ES UN CUADRO INFLAMATORIO CRÓNICO DE LA PIEL DE LOS NIÑOS, QUE PUEDE COMENZAR DESDE LOS 6 MESES EN ADELANTE. SE PRESENTA CON PRURITO Y LESIONES DERMÍTICAS EN ZONAS ESPECÍFICAS PARA CADA EDAD, CON REACTIVACIONES PERIÓDICAS. NO CONTAMOS CON LA CURA PARA ESTE CUADRO. LAS MEDIDAS GENERALES SON BÁSICAS PARA LOGRAR QUE LOS EPISODIOS SEAN LO MÁS ALEJADOS POSIBLES Y LOS MÁS SUAVES.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 6,
        diagnosis: "DERMATITIS DE CONTACTO DE PARPADOS",
        diagnosis_short: "Dermatitis de contacto de párpados",
        triage_seed: "GREEN",
        tags: ["dermatitis", "contacto", "parpados", "prurito", "alergia", "cosmeticos", "hidrocortisona"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- DERMATITIS DE CONTACTO DE PÁRPADOS",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: EVITAR COSMÉTICOS, CREMAS CON RETINOL O MAQUILLAJE, TINTURA PARA EL CABELLO, CONTACTANTES METÁLICOS U OTROS ALÉRGENOS VOLÁTILES COMO DESODORANTES AMBIENTALES O VELAS AROMÁTICAS. 2.- HIDROCORTISONA 1% APLICAR 2 VECES AL DÍA PUNTUAL EN ZONA AFECTADA HASTA MEJORAR LAS LESIONES O X 5 DÍAS CONTINUOS MÁXIMO, LUEGO 1 VEZ AL DÍA X 5 DÍAS Y DESCANSAR 5 DÍAS, REPETIR 2 CICLOS (MEDICAMENTO CANASTA). 3.- LUBRICAR CON CREMA NEUTRA SIN PERFUME. 4.- HIDROXICINA 20MG 1 COMPRIMIDO EN LA NOCHE X 1 MES, SINO TIENEN USAR CLORFENAMINA (MEDICAMENTO CANASTA). 5.- CONTROL POR TELEDERMATOLOGIA 1 MES O SOS.",
        education_text: "EXPLICAR QUE PARA EVITAR LA DERMATITIS DE CONTACTO EN LOS PÁRPADOS ES IMPORTANTE TOMAR ALGUNAS MEDIDAS GENERALES. EVITAR EL USO DE PRODUCTOS IRRITANTES, OPTANDO POR AQUELLOS QUE SEAN HIPOALERGÉNICOS Y SIN FRAGANCIAS, ESPECIALMENTE PARA LA CARA Y LOS OJOS. ES FUNDAMENTAL MANTENER LOS OJOS LIMPIOS, LAVANDO LOS PÁRPADOS CON UN LIMPIADOR SUAVE ESPECÍFICO PARA LA ZONA OCULAR. AL PROBAR NUEVOS PRODUCTOS, REALIZAR UNA PRUEBA EN UNA PEQUEÑA ÁREA DE LA PIEL ANTES DE APLICARLOS EN LOS PÁRPADOS. USO DE GAFAS DE SOL, EVITAR HUMO, POLVO O SUSTANCIAS QUÍMICAS IRRITANTES. MANTENER LA PIEL HIDRATADA CON CREMAS FORMULADAS PARA PIELES SENSIBLES.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 7,
        diagnosis: "DERMATITIS DE CONTACTO",
        diagnosis_short: "Dermatitis de contacto",
        triage_seed: "GREEN",
        tags: ["dermatitis", "contacto", "prurito", "alergia", "clobetasol", "humectacion", "guantes"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- DERMATITIS DE CONTACTO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: USAR GUANTES, EVITAR EL AGUA Y CONTACTANTES METÁLICOS U OTROS. 2.- CLOBETASOL CREMA 0,05% APLICAR 2 VECES AL DÍA X 7 DÍAS EN LESIONES, LUEGO 1 VEZ AL DÍA X 7 DÍAS Y DESCANSAR 14 DÍAS, REPETIR 2 CICLOS (MEDICAMENTO CANASTA). 3.- LUBRICAR CON CREMA HUMECTANTE (MEDICAMENTO CANASTA) O NIVEA TAPA AZUL, LUBRIDERM, PIELARMINA O VASELINA SÓLIDA VARIAS VECES AL DÍA. 4.- HIDROXICINA 20MG 1 COMPRIMIDO EN LA NOCHE X 1 MES, SI NO TIENEN USAR CLORFENAMINA (MEDICAMENTO CANASTA). 5.- CONTROL POR TELEDERMATOLOGIA 1 MES O SOS.",
        education_text: "EXPLICAR QUE LA DERMATITIS DE CONTACTO ES UNA REACCIÓN INFLAMATORIA DE LA PIEL QUE OCURRE CUANDO ÉSTA ENTRA EN CONTACTO CON UNA SUSTANCIA IRRITANTE O ALERGÉNICA. PUEDE MANIFESTARSE DE DOS MANERAS PRINCIPALES: DERMATITIS DE CONTACTO IRRITATIVA Y DERMATITIS DE CONTACTO ALÉRGICA. LA PREVENCIÓN ES CLAVE. EVITAR EL CONTACTO CON SUSTANCIAS IRRITANTES O ALERGÉNICAS CONOCIDAS PUEDE SER FUNDAMENTAL PARA PREVENIR RECURRENCIAS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 8,
        diagnosis: "DERMATITIS MEDICAMENTOSA",
        diagnosis_short: "Dermatitis medicamentosa",
        triage_seed: "YELLOW",
        tags: ["dermatitis", "medicamentosa", "farmacos", "reaccion adversa", "prednisona", "levocetirizina", "derivar"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- DERMATITIS MEDICAMENTOSA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- SUSPENDER EL FÁRMACO QUE PUDO HABER PROVOCADO ESTE CUADRO Y EVITAR CONSUMIR NUEVAMENTE. 2.- PREDNISONA 20MG AL DÍA POR 3 DÍAS. 3.- LEVOCETIRIZINA 5MG 1 COMP CADA 12H HASTA MEJORAR EL CUADRO (MEDICAMENTOS DE CANASTA). 4.- DERIVAR EN CASO DE PERSISTIR EL CUADRO PARA CONTROL PRESENCIAL.",
        education_text: "EXPLICAR QUE LAS ERUPCIONES CUTÁNEAS SON UNA DE LAS MANIFESTACIONES MÁS FRECUENTES DE LAS REACCIONES ADVERSAS A DROGAS. EXISTEN DIVERSOS PATRONES CLÍNICOS, PERO NINGUNO DE ELLOS ES ESPECÍFICO PARA UNA DETERMINADA DROGA. LOS MECANISMOS INVOLUCRADOS PUEDEN SER INMUNOLÓGICOS O NO INMUNOLÓGICOS, SIENDO ESTOS ÚLTIMOS LOS MÁS FRECUENTES.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 9,
        diagnosis: "DERMATITIS SEBORREICA",
        diagnosis_short: "Dermatitis seborreica",
        triage_seed: "GREEN",
        tags: ["dermatitis", "seborreica", "caspa", "ketoconazol", "descamacion", "rostro", "cuero cabelludo", "cronico"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- DERMATITIS SEBORREICA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- USAR SHAMPOO ANTICASPA Y EN CASO DE BROTES: 2.- KETOCONAZOL SHAMPOO 2% USAR 3 VECES POR SEMANA DEJANDO LA ESPUMA 5 MINUTOS EN CUERO CABELLUDO, OREJAS Y ZONAS DESCAMADAS DEL ROSTRO HASTA MEJORAR EL BROTE (MEDICAMENTO DE CANASTA). 3.- APLICAR KETOCONAZOL CREMA 2% EN ZONAS DESCAMADAS DEL ROSTRO MAÑANA Y NOCHE HASTA MEJORAR. REPETIR APLICACIÓN SI REAPARECE. 4.- LAVAR ROSTRO Y PÁRPADOS CON NEOLUCID LOCIÓN LIMPIADORA MAÑANA Y NOCHE DE FORMA PERMANENTE. ENVIAR NUEVA TELECONSULTA EN 3 MESES PARA EVALUAR RESPUESTA AL TRATAMIENTO.",
        education_text: "EXPLICAR QUE SE TRATA DE UNA CONDICIÓN CRÓNICA, CON BROTES QUE SE PUEDEN RELACIONAR CON ESTRÉS FÍSICO O MENTAL.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 10,
        diagnosis: "ECCEMA HIPOSTATICO",
        diagnosis_short: "Eccema hipostático",
        triage_seed: "YELLOW",
        tags: ["eccema", "hipostatico", "insuficiencia venosa", "piernas", "clobetasol", "edema", "prurito", "vaselina"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ECCEMA HIPOSTÁTICO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: REALIZAR MEDIDAS GENERALES COMO COMPRESIÓN ELÁSTICA EN CASO DE EDEMA, FORTALECER LA MUSCULATURA DE LAS EXTREMIDADES INFERIORES Y EVITAR EL CONTACTO DIRECTO DE LAS PIERNAS CON PRODUCTOS IRRITANTES PARA LA PIEL COMO DETERGENTES O LIMPIADORES. EVITAR EL RASCADO. APLICAR CLOBETASOL 0,05% CREMA DOS VECES AL DÍA EN LAS LESIONES HASTA MEJORAR O MÁXIMO 5 DÍAS DE LA SEMANA POR 1 MES. LUBRICACIÓN DE LA PIEL CON VASELINA SÓLIDA 2 VECES AL DÍA. ENVIAR NUEVA TELECONSULTA EN 1 MES PARA REEVALUAR.",
        education_text: "EXPLICAR QUE LA DERMATITIS POR ESTASIS ES LA INFLAMACIÓN DE LA PIEL DE LOS MIEMBROS INFERIORES POR INSUFICIENCIA VENOSA CRÓNICA. LOS SÍNTOMAS SON PRURITO, DESCAMACIÓN, HIPERPIGMENTACIÓN Y EN OCASIONES ULCERACIÓN. EL DIAGNÓSTICO ES CLÍNICO. EL TRATAMIENTO ESTÁ DIRIGIDO A LA INSUFICIENCIA VENOSA CRÓNICA Y A PREVENIR LA OCURRENCIA O LA PROGRESIÓN DE LAS ÚLCERAS ASOCIADAS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 11,
        diagnosis: "ECCEMA NUMULAR",
        diagnosis_short: "Eccema numular",
        triage_seed: "GREEN",
        tags: ["eccema", "numular", "prurito", "piernas", "clobetasol", "humectacion", "mupirocina"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ECCEMA NUMULAR",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- APLICAR CREMA HUMECTANTE NEUTRA SIN PERFUME O VASELINA SÓLIDA DE FORMA DIARIA EN PIERNAS (IDEAL 3 VECES AL DÍA) POR UN MES. 2.- CLOBETASOL 0,05% CREMA APLICAR 2 VECES AL DÍA POR 5 DÍAS DE LA SEMANA HASTA MEJORAR JUNTO A MUPIROCINA CREMA APLICAR 2 VECES AL DÍA. SI NO CEDE, SUSPENDER 2 DÍAS Y REPETIR ESQUEMA POR 3 SEMANAS. 3.- EN CASO DE PRURITO: CETIRIZINA 10 MG 1 COMP CADA 12 HRS POR 14 DÍAS. 4.- ENVIAR NUEVA TELECONSULTA PARA CONTROL EN CASO DE PERSISTIR LAS LESIONES.",
        education_text: "EXPLICAR QUE DEBE BAÑARSE MÁX 5 MINUTOS, AGUA TIBIA, JABÓN NEUTRO. EVITAR EL CONTACTO DIRECTO DE LAS PIERNAS CON PRODUCTOS IRRITANTES PARA LA PIEL. USAR DETERGENTES HIPOALÉRGÉNICOS PARA LAVADO DE ROPA DIARIA. EVITAR EL RASCADO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 12,
        diagnosis: "ONICOMICOSIS",
        diagnosis_short: "Onicomicosis",
        triage_seed: "YELLOW",
        tags: ["onicomicosis", "uñas", "hongos", "terbinafina", "dermatofitos", "calzado", "micosis"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ONICOMICOSIS",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- TERBINAFINA 250MG AL DÍA X 12 SEMANAS (EVALUAR QUE EL PACIENTE NO ESTÉ TOMANDO ESTATINAS O FIBRATOS O QUE TENGA OTRA CONTRAINDICACIÓN PARA SU USO) (MEDICAMENTO DE CANASTA). SI PACIENTE TIENE POLIFARMACIA HACER CONTROL DE PERFIL HEPÁTICO, HEMOGRAMA Y FUNCIÓN RENAL AL MES Y A LOS 3 MESES. 2.- CONTROL X TELEDERMATOLOGIA EN 3 MESES CON ESTAS Y NUEVAS FOTOS.",
        education_text: "EXPLICAR QUE SE DEBE ACONSEJAR AL PACIENTE: USO DE CALZADOS RESPIRABLES O USO EL MENOR TIEMPO POSIBLE DE CALZADOS MUY OCLUSIVOS. USO DE CALCETINES DE ALGODÓN, USO DE ALGÚN TALCO ANTIMICÓTICO EN EL CALZADO. FRECUENTE CORTE DE UÑAS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 13,
        diagnosis: "PSORIASIS VULGAR LEVE",
        diagnosis_short: "Psoriasis vulgar leve",
        triage_seed: "YELLOW",
        tags: ["psoriasis", "placas", "descamacion", "clobetasol", "acido salicilico", "urea", "prurito", "cronico"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- PSORIASIS VULGAR LEVE",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: HUMECTAR PIEL CON CREMA SIN PERFUMES (LUBRIDERM) O VASELINA SÓLIDA. 2.- PARA PLACAS LOCALIZADAS EN TRONCO Y EXTREMIDADES: RECETA MAGISTRAL: CLOBETASOL 0,05% + ÁCIDO SALICÍLICO 4% + UREA 10% EN CREMA NOVOBASE II O UNGÜENTO CSP: 80 GRS. APLICAR EN PLACAS 2 VECES AL DÍA POR 10–14 DÍAS, LUEGO MANTENER UNA VEZ EN LA NOCHE SOLO SÁBADO Y DOMINGO POR UN MES. ALTERNATIVA (CANASTA): CLOBETASOL UNGÜENTO 0.05%. EN ZONAS DE PLIEGUES EVITAR CLOBETASOL Y PREFERIR HIDROCORTISONA CREMA O TACROLIMUS 0,1% UNGÜENTO. 3.- SI HAY MUCHO PRURITO: LEVOCETIRIZINA 5 MG 1 COMP CADA 12 HRS POR UN MES. 4.- ENVIAR NUEVA TELECONSULTA EN 3 MESES EN CASO DE PERSISTENCIA Y/O PROGRESIÓN DE LESIONES PARA EVALUAR DERIVACIÓN A NIVEL SECUNDARIO.",
        education_text: "EXPLICAR QUE ESTA ES UNA ENFERMEDAD DE CARÁCTER CRÓNICO Y RECURRENTE. INSISTIR EN QUE LA CLAVE PARA EVITAR REBROTES ES MANEJO DEL ESTRÉS, LUBRICACIÓN DE LA PIEL CON CREMAS NEUTRAS SIN PERFUME (EJ. LUBRIDERM) Y EVITAR EL RASCADO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 14,
        diagnosis: "PSORIASIS VULGAR SEVERA",
        diagnosis_short: "Psoriasis vulgar severa",
        triage_seed: "RED",
        tags: ["psoriasis", "severa", "placas", "descamacion", "clobetasol", "derivar", "control presencial", "artritis psoriatica"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- PSORIASIS VULGAR SEVERA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: LUBRICACIÓN DIARIA CON VASELINA SÓLIDA Y EVITAR RASCADO Y EPISODIOS DE ESTRÉS. 2.- CLOBETASOL CREMA 0,05% APLICAR EN LA MAÑANA Y EN LA NOCHE EN LESIONES X 14 DÍAS, LUEGO 1 VEZ AL DÍA X 14 DÍAS Y DESCANSAR 14 DÍAS. REPETIR EL CICLO SI QUEDAN LESIONES. RECETARIO MAGISTRAL ALTERNATIVO: CLOBETASOL 0,05%, ÁCIDO SALICÍLICO 5%, CLOTRIMAZOL 1%, UREA 5%, CREMA BASE CSP 150GRS. 3.- HIDROXICINA 20MG 1 COMPRIMIDO EN LA NOCHE EN CASO DE PRURITO, SINO TIENEN USAR CLORFENAMINA 4MG. 4.- CONTROL PRESENCIAL PARA EVALUAR COMBINACIÓN DE TRATAMIENTOS.",
        education_text: "EXPLICAR QUE ESTA ES UNA ENFERMEDAD DE CARÁCTER CRÓNICO Y RECURRENTE. INSISTIR EN QUE LA CLAVE PARA EVITAR REBROTES ES MANEJO DEL ESTRÉS, EVITAR CONSUMO DE ALCOHOL Y TABACO, CONTROL METABÓLICO, LUBRICACIÓN DE LA PIEL CON CREMAS NEUTRAS SIN PERFUME Y EVITAR EL RASCADO. ATENTO AL COMPROMISO UNGUEAL Y/O ARTRALGIAS DE MANOS, CADERAS, RODILLAS Y DOLOR DE TALÓN COMO MARCADOR DE ARTRITIS PSORIÁTICA (EN TAL CASO, DERIVAR A REUMATOLOGÍA).",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 15,
        diagnosis: "ROSACEA ERITEMATO-TELANGIECTASICA",
        diagnosis_short: "Rosácea eritematotelangiectásica",
        triage_seed: "GREEN",
        tags: ["rosacea", "eritema", "telangiectasias", "facial", "metronidazol", "fotoproteccion", "cronico"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ROSACEA ERITEMATO-TELANGIECTÁSICA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- EVITAR TODO LO QUE LE PRODUZCA SENSACIÓN DE CALOR EN LA CARA: EVITAR EL SOL, CALOR, CHOCOLATE, AJÍ Y ALIÑOS, ALCOHOL, CAFÉ, FRUTOS SECOS, ESTRÉS, ENTRE OTROS. 2.- METRONIDAZOL 0.75% EN CREMA O GEL, APLICAR CAPA FINA TODAS LAS NOCHES EN LA CARA X 3 MESES (MEDICAMENTO DE CANASTA). 3.- PROTECCIÓN SOLAR CON FPS 50+ MAÑANA Y MEDIO DÍA O CADA 2 HORAS SI ESTÁ AL SOL. 4.- CONTROL POR TELEDERMATOLOGIA EN 3 MESES.",
        education_text: "EXPLICAR QUE ESTA ES UNA ENFERMEDAD DE CARÁCTER CRÓNICO Y RECURRENTE. INSISTIR EN QUE LA CLAVE PARA EVITAR REBROTES ES MANEJO DEL ESTRÉS, EVITAR LOS GATILLANTES DE ROSÁCEA Y MANTENER EL TRATAMIENTO A PERMANENCIA.",
        source: "PROTOCOLOS TD 2023"
    }
    ,
    {
        id: 16,
        diagnosis: "ROSACEA PAPULO PUSTULAR",
        diagnosis_short: "Rosácea papulopustular",
        triage_seed: "YELLOW",
        tags: ["rosacea", "papulopustular", "pustulas", "facial", "metronidazol", "doxiciclina", "antibiotico oral", "cronico"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- ROSACEA PAPULO PUSTULAR",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- EVITAR TODO LO QUE LE PRODUZCA SENSACIÓN DE CALOR EN LA CARA: EVITAR EL SOL, CALOR, CHOCOLATE, AJÍ Y ALIÑOS, ALCOHOL, CAFÉ, FRUTOS SECOS, ESTRÉS, ENTRE OTROS. 2.- METRONIDAZOL 0.75% EN CREMA O GEL, APLICAR CAPA FINA TODAS LAS NOCHES EN LA CARA X 3 MESES (MEDICAMENTO DE CANASTA). 3.- PROTECCIÓN SOLAR CON FPS 50+ MAÑANA Y MEDIO DÍA O CADA 2 HORAS SI ESTÁ AL SOL. 4.- DOXICICLINA 100MG 1 COMP EN LAS NOCHES, DESPUÉS DE LAS COMIDAS X 6 SEMANAS SIN LECHE (MEDICAMENTO DE CANASTA). SINO HAY USAR OTRAS TETRACICLINAS EN LA NOCHE X MISMO PERIODO O ERITROMICINA 500MG, 1 COMP CADA 12 HORAS X 6 SEMANAS. 5.- CONTROL POR TELEDERMATOLOGIA EN 3 MESES.",
        education_text: "EXPLICAR QUE ESTA ES UNA ENFERMEDAD DE CARÁCTER CRÓNICO Y RECURRENTE. INSISTIR EN QUE LA CLAVE PARA EVITAR REBROTES ES MANEJO DEL ESTRÉS, EVITAR LOS GATILLANTES DE ROSÁCEA Y MANTENER EL TRATAMIENTO A PERMANENCIA.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 17,
        diagnosis: "VITILIGO GENERALIZADO",
        diagnosis_short: "Vitiligo generalizado",
        triage_seed: "RED",
        tags: ["vitiligo", "hipopigmentacion", "generalizado", "autoinmune", "derivar", "control presencial", "fotoproteccion"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- VITILIGO GENERALIZADO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: PROTECCIÓN SOLAR ESTRICTA SPF50+ MAÑANA Y MEDIO DÍA Y CADA 2 HORAS SI ESTÁ AL SOL. 2.- HIDROCORTISONA CREMA 1% APLICAR 1 VEZ AL DÍA UNA CAPA FINA DE LUNES A VIERNES EN ZONAS DE VITILIGO HASTA EL CONTROL PRESENCIAL (MEDICAMENTO CANASTA). 3.- DERIVAR A CONTROL PRESENCIAL PARA ESTUDIO Y MANEJO.",
        education_text: "EXPLICAR QUE LA RESPUESTA ES LENTA Y MIENTRAS MÁS TIEMPO DE EVOLUCIÓN LLEVE EL VITILIGO, MENOR PROBABILIDAD EXISTE DE REPIGMENTAR. MÁS DIFÍCIL EN LAS MANOS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 18,
        diagnosis: "VITILIGO LOCALIZADO",
        diagnosis_short: "Vitiligo localizado",
        triage_seed: "YELLOW",
        tags: ["vitiligo", "hipopigmentacion", "localizado", "autoinmune", "clobetasol", "fotoproteccion", "tiroides"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- VITILIGO LOCALIZADO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: PROTECCIÓN SOLAR ESTRICTA SPF50+ MAÑANA Y MEDIO DÍA Y CADA 2 HORAS SI ESTÁ AL SOL. 2.- CLOBETASOL 0,05% CREMA APLICAR 1 VEZ AL DÍA UNA CAPA FINA X 3 SEMANAS, DESCANSAR 1 SEMANA Y REPETIR EL CICLO POR 3 VECES (MEDICAMENTO CANASTA). 3.- TOMAR EXÁMENES: TSH, ANA, HEMOGRAMA, SOLO SI SE PUEDE EN APS. 4.- CONTROL EN 3 MESES X TELEDERMATOLOGIA CON ESTAS FOTOS Y CON LAS NUEVAS. 5.- SOLICITAR EXÁMENES GENERALES DISPONIBLES EN SU CENTRO (IMPORTANTE EVALUAR HEMOGRAMA, PRUEBAS TIROIDEAS Y PERFIL BIOQUÍMICO).",
        education_text: "EXPLICAR QUE ES UNA PATOLOGÍA AUTOINMUNE, POSIBLEMENTE ASOCIADA A OTRAS PATOLOGÍAS AUTOINMUNES POR LO QUE ES NECESARIO EXÁMENES DE LABORATORIO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 19,
        diagnosis: "DISHIDROSIS PALMAR",
        diagnosis_short: "Dishidrosis palmar",
        triage_seed: "YELLOW",
        tags: ["dishidrosis", "palmas", "vesiculas", "ampollas", "prurito", "clobetasol", "humectacion"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: 1.- DISHIDROSIS PALMAR",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: APLICACIÓN DOS VECES AL DÍA DE CORTICOIDES TÓPICOS DE ALTA POTENCIA: CLOBETASOL 0,05% CREMA EN AMPOLLAS Y ZONAS CON PRURITO HASTA MEJORAR. LO HABITUAL ES QUE AL REMITIR EL CUADRO QUEDA LA PIEL DESCAMADA, LA CUAL SE PUEDE REPARAR MÁS RÁPIDO APLICANDO TRAS CADA LAVADO CREMA HUMECTANTE DE MANOS (PREFERIR AQUELLAS NEUTRAS SIN PERFUME).",
        education_text: "EXPLICAR QUE LA CAUSA DE LA DISHIDROSIS NO ESTÁ BIEN ENTENDIDA, PERO SE CREE QUE ESTÁ RELACIONADA CON UNA COMBINACIÓN DE FACTORES GENÉTICOS Y AMBIENTALES. ALGUNOS POSIBLES DESENCADENANTES INCLUYEN EL ESTRÉS, LA EXPOSICIÓN A ALÉRGENOS O IRRITANTES Y LOS CAMBIOS EN EL CLIMA O LA TEMPERATURA. LOS SÍNTOMAS PUEDEN INCLUIR PEQUEÑAS AMPOLLAS LLENAS DE LÍQUIDO QUE SON PRURIGINOSAS O DOLOROSAS, ENROJECIMIENTO E INFLAMACIÓN DEL ÁREA AFECTADA Y DESCAMACIÓN DE LA PIEL. EN CASOS GRAVES, LAS AMPOLLAS PUEDEN INFECTARSE.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 20,
        diagnosis: "DERMATITIS DE CONTACTO GENERAL",
        diagnosis_short: "Dermatitis de contacto general",
        triage_seed: "GREEN",
        tags: ["dermatitis", "contacto", "alergia", "irritante", "clobetasol", "loratadina", "humectacion"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: DERMATITIS DE CONTACTO GENERAL",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: TRAS CADA DUCHA APLICAR CREMA HUMECTANTE NEUTRA SIN PERFUME EN TODO EL CUERPO. CLOBETASOL 0,05% CREMA: APLICAR 2 VECES AL DÍA EN PLACAS DE DERMATITIS MÁXIMO DE LUNES A VIERNES EN CASO DE PRURITO O ERITEMA; SI PERSISTE, SUSPENDER 2 DÍAS Y LUEGO REAPLICAR HASTA MEJORAR. PUEDE RECOMENDAR TAMBIÉN MANTENER ANTIHISTAMÍNICOS: LORATADINA 10MG CADA 12H HASTA CEDER EL CUADRO. ENVIAR NUEVA TELECONSULTA SI PERSISTE EN 1 MES.",
        education_text: "EXPLICAR QUE ESTO PUEDE SER GATILLADO POR EL CONTACTO CON ALGÚN ALÉRGENO. DEBE EVITAR EL CONTACTO DIRECTO CON PRODUCTOS IRRITANTES PARA LA PIEL COMO PERFUMES, DETERGENTES CON MUCHO PERFUME (PREFERIR POPEYE LÍQUIDO), JABONES, MATERIAL DE LA ROPA (USAR SOLO PRENDAS DE ALGODÓN), METALES (HEBILLAS DE CINTURÓN, BOTONES METÁLICOS). EVITAR EL RASCADO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 21,
        diagnosis: "FOLICULITIS SUPERFICIAL",
        diagnosis_short: "Foliculitis superficial",
        triage_seed: "GREEN",
        tags: ["foliculitis", "superficial", "bacteria", "clindamicina", "jabon astringente", "seborrea", "humedad"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: FOLICULITIS SUPERFICIAL",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: EL USO RUTINARIO DE JABONES ASTRINGENTES EN LA DUCHA (ZASTIC BARRA, DERMATOPIC SULFUR O SOLO JABÓN DE GLICERINA) AYUDA A EVITAR NUEVOS BROTES. PUEDE INDICAR ADEMÁS UNA CLINDAMICINA 1% GEL O CREMA, APLICAR UNA CAPA FINA EN LESIONES DOS VECES AL DÍA HASTA MEJORAR.",
        education_text: "EXPLICAR AL PACIENTE QUE ESTO ES MULTIFACTORIAL Y PUEDE SER GATILLADO POR HUMEDAD (SUDOR EN CONTACTO PROLONGADO CON LA PIEL), AUMENTO DE LA SEBORREA, ESTRÉS, ENTRE OTROS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 22,
        diagnosis: "PSORIASIS EN PLACAS CON COMPROMISO DE CUERO CABELLUDO",
        diagnosis_short: "Psoriasis en placas con compromiso de cuero cabelludo",
        triage_seed: "YELLOW",
        tags: ["psoriasis", "placas", "cuero cabelludo", "clobetasol", "acido salicilico", "descamacion", "cronico"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: PSORIASIS EN PLACAS CON COMPROMISO DE CUERO CABELLUDO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: CLOBETASOL CREMA 0.05% TÓPICO + VASELINA SALICILADA (EN CASO DE NO PODER COSTEAR RECETA MAGISTRAL), APLICANDO EN PLACAS 2 VECES AL DÍA HASTA MEJORAR O MÁXIMO DE LUNES A VIERNES, SUSPENDIENDO SÁBADO Y DOMINGO HASTA MEJORAR. EN CASO DE REAPARECER PLACAS, REPETIR EL ESQUEMA. EN CASO DE QUE LA PACIENTE PUEDA COSTEARLO, RECETA MAGISTRAL: CLOBETASOL 0,05% + ÁCIDO SALICÍLICO 4% EN CREMA LÍQUIDA CSP: 60 GRS, APLICAR EN PLACAS DEL CUERO CABELLUDO 2 VECES AL DÍA HASTA MEJORAR O MÁXIMO DE LUNES A VIERNES. ENVIAR NUEVA TELECONSULTA PARA EVALUAR RESPUESTA AL TRATAMIENTO LUEGO DE 1 MES.",
        education_text: "EXPLICAR QUE ESTA ES UNA ENFERMEDAD DE CARÁCTER CRÓNICO Y RECURRENTE, CON BROTES.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 23,
        diagnosis: "HIDROSADENITIS SUPURATIVA",
        diagnosis_short: "Hidradenitis supurativa",
        triage_seed: "YELLOW",
        tags: ["hidradenitis", "supurativa", "abscesos", "nodulos", "clindamicina", "doxiciclina", "resorcinol", "folicular"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: HIDROSADENITIS SUPURATIVA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- CLINDAMICINA 1% EN GEL ES EL MEDICAMENTO TÓPICO MÁS ESTUDIADO Y UTILIZADO. APLICAR DOS VECES AL DÍA POR UN MES. REDUCE ABSCESOS Y PÚSTULAS, PERO NO TIENE EFECTO SOBRE LOS NÓDULOS. 2.- SI PERSISTE INDICAR DOXICICLINA 100 MG 1 COMP/DÍA POR 2 MESES. SI ES POSIBLE ASOCIAR CON RECETA MAGISTRAL: RESORCINOL 15% CREMA BASE CSP: 30 GRS, APLICAR UNA CAPA FINA EN LAS NOCHES EN ZONAS DE LESIONES. 3.- ENVIAR NUEVA TELECONSULTA EN 3 MESES PARA EVALUAR RESPUESTA A TRATAMIENTO. SI PERSISTE HAY QUE EVALUAR CON ECO PARTES BLANDAS Y EVENTUAL MANEJO QUIRÚRGICO.",
        education_text: "EXPLICAR QUE LA HIDRADENITIS SUPURATIVA (HS) ES UNA ENFERMEDAD INFLAMATORIA CUTÁNEA CRÓNICA Y RECURRENTE DEL FOLÍCULO PILOSO. MEDIDAS GENERALES: 1.- ASEO LOCAL SUAVE CON JABÓN HIPOALÉRGÉNICO, SIN FRICCIÓN. 2.- REDUCCIÓN DEL TRAUMA EN ZONAS AFECTADAS (ROPA INTERIOR HOLGADA Y DE ALGODÓN, NO SINTÉTICA). EVITAR DESODORANTE ANTITRANSPIRANTE. 3.- SI HAY ANTECEDENTE DE OBESIDAD O SOBREPESO, INDICAR TRATAMIENTO. 4.- SUSPENDER EL TABAQUISMO. APOYO PSICOLÓGICO SEGÚN SEA NECESARIO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 24,
        diagnosis: "ALOPECIA AREATA",
        diagnosis_short: "Alopecia areata",
        triage_seed: "YELLOW",
        tags: ["alopecia", "areata", "cuero cabelludo", "autoinmune", "minoxidil", "clobetasol", "tiroides", "caida de pelo"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: ALOPECIA AREATA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- SOLICITUD DE FUNCIÓN TIROIDEA (TSH Y T4 LIBRE) Y ANTICUERPOS ANTI-TIROIDEOS (AC ANTITIROPEROXIDASA Y ANTI-TIROGLOBULINA). 2.- TERAPIA TÓPICA: RECETA MAGISTRAL: MINOXIDIL 5% LOCIÓN CAPILAR CSP 100 ML. APLICAR 1 ML UNA VEZ AL DÍA (MAÑANA) POR 2 MESES. ALTERNATIVA: ANAGEN 5%, ALOPEK 5% (LOCIÓN O ESPUMA). CLOBETASOL 0,05% CREMA O UNGÜENTO: APLICAR UNA VEZ EN LA NOCHE EN PLACA DE ALOPECIA DURANTE 2 MESES. 3.- EVENTUAL DERIVACIÓN EN CASO DE MALA RESPUESTA, AVANCE DE LAS LESIONES O APARICIÓN DE NUEVAS ZONAS DE ALOPECIA.",
        education_text: "EXPLICAR QUE SE TRATA DE UNA CONDICIÓN AUTOINMUNE DEL CUERO CABELLUDO, QUE PODRÍA ESTAR EN RELACIÓN A ALGÚN EVENTO EMOCIONAL IMPORTANTE (SIEMPRE DESCARTAR TRASTORNO PSIQUIÁTRICO ASOCIADO) O ESTAR ASOCIADA A OTRA ENFERMEDAD AUTOINMUNE.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 25,
        diagnosis: "PITIRIASIS VERSICOLOR",
        diagnosis_short: "Pitiriasis versicolor",
        triage_seed: "GREEN",
        tags: ["pitiriasis", "versicolor", "hongos", "ketoconazol", "fluconazol", "hipopigmentacion", "descamacion"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: PITIRIASIS VERSICOLOR",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: SUGIERO MANEJAR CON KETOCONAZOL CHAMPÚ USÁNDOLO PARA JABONAR LAS ZONAS AFECTADAS A DIARIO DEJANDO LA ESPUMA ACTUAR 3 A 5 MINUTOS POR 2 SEMANAS. EN CASO DE NO TENER CONTRAINDICACIONES SUGIERO MANEJAR CON FLUCONAZOL 150 MG 1 COMPRIMIDO A LA SEMANA POR 4 SEMANAS.",
        education_text: "EXPLICAR QUE ES ESPERABLE QUE POST TRATAMIENTO EVOLUCIONE CON MEJORA DE LA DESCAMACIÓN, PERO LA HIPOPIGMENTACIÓN PUEDE PERSISTIR POR VARIOS MESES. EN CASO DE DUDAS ENVIAR NUEVA TELECONSULTA.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 26,
        diagnosis: "MELASMA",
        diagnosis_short: "Melasma",
        triage_seed: "GREEN",
        tags: ["melasma", "cloasma", "hiperpigmentacion", "rostro", "fotoproteccion", "hormonal", "manchas"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: MELASMA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: PUEDE RECOMENDAR FOTOPROTECCIÓN ESTRICTA CADA 3–4H CON FOTOPROTECTOR 50+ OIL FREE O NO COMEDOGÉNICO. EN CASO QUE EL PACIENTE LO PUEDA COSTEAR, RECETA MAGISTRAL: CHROMABRIGHT 0,5% ARBUTIN 4% ÁCIDO KOJICO 4% ALFABISABOLOL 1% ÁCIDO TRANEXÁMICO 3% EN CREMA BASE NO COMEDOGÉNICA CSP: 30 GRS. APLICAR EN ROSTRO MAÑANA Y NOCHE LUEGO DE LAVAR CON SOLUCIONES DE LIMPIEZA PARA PIEL SENSIBLE. REPETIR RECETA POR 6 VECES. ENVIAR NUEVA TELECONSULTA LUEGO DE COMPLETAR 6 MESES DE TRATAMIENTO.",
        education_text: "EXPLICAR QUE MELASMA O CLOASMA ES UNA CONDICIÓN BENIGNA Y CRÓNICA DE LA PIEL, DONDE LA EXPOSICIÓN AL SOL, A LA LUZ VISIBLE Y LOS CAMBIOS HORMONALES PUEDEN REACTIVARLO.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 27,
        diagnosis: "URTICARIA CRONICA",
        diagnosis_short: "Urticaria crónica",
        triage_seed: "RED",
        tags: ["urticaria", "cronica", "ronchas", "prurito", "autoinmune", "antihistaminico", "derivar", "examenes"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: URTICARIA CRÓNICA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: SOLICITAR EXÁMENES GENERALES: HEMOGRAMA VHS, VDRL, TSH T4 LIBRE, ORINA COMPLETA, COPROCULTIVO, PERFIL BIOQUÍMICO. DERIVAR A CONTROL PRESENCIAL CON EXÁMENES SOLICITADOS. MANTENER ANTIHISTAMÍNICOS (LEVOCETIRIZINA 5MG CADA DÍA E HIDROXICINA 20MG 1 COMP CADA NOCHE) PERMANENTEMENTE HASTA CONTROL PRESENCIAL.",
        education_text: "EXPLICAR QUE EN LA MITAD DE LOS CASOS DE URTICARIA CRÓNICA SON DE ORIGEN AUTOINMUNE. ENTRE LOS FACTORES QUE PUEDEN AGRAVAR O DESENCADENAR LA URTICARIA CRÓNICA SE CONTEMPLAN: MEDICAMENTOS (ANTIBIÓTICOS, AINES, ASPIRINA), ALIMENTOS Y ADITIVOS ALIMENTARIOS, ESTÍMULOS FÍSICOS (LÁTEX, TEMPERATURA, SOL), ESTRÉS Y PREDISPOSICIÓN GENÉTICA. ENTRE LAS PATOLOGÍAS ASOCIADAS DESTACAN ENFERMEDADES TIROIDEAS, ARTRITIS REUMATOIDE, LES, INFECCIONES BACTERIANAS, VIRALES Y PARASITOSIS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 28,
        diagnosis: "LIQUEN SIMPLE CRONICO",
        diagnosis_short: "Liquen simple crónico",
        triage_seed: "YELLOW",
        tags: ["liquen", "simple cronico", "prurito", "engrosamiento cutaneo", "clobetasol", "humectacion", "grataje"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: LIQUEN SIMPLE CRÓNICO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: LO FUNDAMENTAL PARA MEJORAR ES EVITAR EL GRATAJE Y LA LUBRICACIÓN DE LA PIEL CON CREMAS DE MANOS NEUTRAS SIN PERFUME O VASELINA SÓLIDA TRAS CADA LAVADO DE MANOS, ASÍ COMO EVITAR EL CONTACTO DE LA PIEL CON IRRITANTES (DETERGENTES O LIMPIADORES). SOLO EN CASO DE BROTE DE PRURITO O ERITEMA APLICAR CLOBETASOL 0,05%, 2 VECES AL DÍA MÁXIMO POR 5 DÍAS A LA SEMANA POR 1 MES. SI PERSISTE, ENVIAR NUEVA TELECONSULTA EN 1 MES.",
        education_text: "EXPLICAR QUE EL LIQUEN SIMPLE CRÓNICO ES LA INFLAMACIÓN Y ENGROSAMIENTO CUTÁNEO PROVOCADO POR LA FALTA DE LUBRICACIÓN Y GRATAJE CRÓNICO DE LA PIEL, QUE SE EXACERBA EN PERÍODOS DE ESTRÉS O DE CONTACTO CON IRRITANTES.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 29,
        diagnosis: "QUERATOSIS ACTINICA",
        diagnosis_short: "Queratosis actínica",
        triage_seed: "RED",
        tags: ["queratosis actinica", "lesion pigmentada", "cancer de piel", "fotoproteccion", "derivar", "especialista", "fotoexpuesto"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: QUERATOSIS ACTÍNICA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: USO RUTINARIO DE FILTRO SOLAR. DERIVAR PARA MANEJO POR ESPECIALISTA PRESENCIAL.",
        education_text: "EXPLICAR QUE AUNQUE LA QUERATOSIS ACTÍNICA NO SUELE SER DOLOROSA, PUEDE SER UNA SEÑAL DE QUE LA PIEL HA SUFRIDO DAÑOS POR LA EXPOSICIÓN AL SOL Y AUMENTA EL RIESGO DE DESARROLLAR CÁNCER DE PIEL EN EL FUTURO. EL TRATAMIENTO GENERALMENTE IMPLICA LA ELIMINACIÓN DE LA LESIÓN MEDIANTE CRIOTERAPIA, CIRUGÍA O TERAPIA FOTODINÁMICA. LA PREVENCIÓN ES LA MEJOR ESTRATEGIA: USAR ROPA PROTECTORA, SOMBREROS DE ALA ANCHA, PROTECTOR SOLAR CON FPS ≥30 Y EVITAR LA EXPOSICIÓN AL SOL EN LAS HORAS PICO (10 A.M. A 4 P.M.).",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 30,
        diagnosis: "URTICARIA AGUDA",
        diagnosis_short: "Urticaria aguda",
        triage_seed: "YELLOW",
        tags: ["urticaria", "aguda", "ronchas", "prurito", "antihistaminico", "levocetirizina", "dieta"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: URTICARIA AGUDA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- ANTIHISTAMÍNICOS DE 2.ª GENERACIÓN: LEVOCETIRIZINA 5 MG HASTA 2 COMPRIMIDOS CADA 12 H (MÁXIMO) HASTA CEDER LAS RONCHAS. 2.- CORTICOIDES ORALES NO SIRVEN MUCHO Y DEBE DESCARTARSE INFECCIÓN VIRAL/BACTERIANA PREVIO A SU USO. 3.- ENVIAR NUEVA TELECONSULTA EN CASO DE MALA RESPUESTA AL TRATAMIENTO O QUE SE PROLONGUE MÁS DE 6 SEMANAS (URTICARIA CRÓNICA).",
        education_text: "EXPLICAR QUE DEBE EVITAR LOS SIGUIENTES ALIMENTOS Y MEDICAMENTOS: CLARA DE HUEVO, MANÍ, NUECES Y ALMENDRAS, POROTO DE SOYA, PESCADOS, MARISCOS Y CRUSTÁCEOS, YOGURES Y POSTRES ENVASADOS, HELADOS Y GOLOSINAS, PAPAS FRITAS, KÉTCHUP Y COMIDA CHATARRA EN GENERAL, GELATINAS, BEBIDAS Y JUGOS DE FANTASÍA EN SOBRE O CAJA, LECHE CON COLORANTES ARTIFICIALES, ALIMENTOS EMBUTIDOS (CECINAS, VIENESAS, PATÉ), JARABES PARA LA TOS Y GELES. TAMBIÉN EVITAR TODOS LOS ALIMENTOS EN CAJAS, SOBRES O LATAS QUE POSEEN PRESERVANTES Y COLORANTES. EN CASO DE SIGNOS DE ALARMA (AUMENTO DE VOLUMEN DE MUCOSA ORAL-CONJUNTIVAL) O COMPROMISO DEL ESTADO GENERAL, RECONSULTAR.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 31,
        diagnosis: "ACANTOSIS NIGRICANS",
        diagnosis_short: "Acantosis nigricans",
        triage_seed: "YELLOW",
        tags: ["acantosis nigricans", "hiperpigmentacion", "resistencia insulina", "diabetes", "pliegues", "metabolico"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: ACANTOSIS NIGRICANS",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: MANEJO DE COMORBILIDADES.",
        education_text: "EXPLICAR QUE EL TRATAMIENTO DE LA ACANTOSIS NIGRICANS SE CENTRA EN ABORDAR LA CAUSA SUBYACENTE. SI SE IDENTIFICA UNA RESISTENCIA A LA INSULINA O DIABETES, SE PUEDEN RECOMENDAR CAMBIOS EN EL ESTILO DE VIDA COMO UNA DIETA SALUDABLE Y EJERCICIO REGULAR, ADEMÁS DE MEDICAMENTOS SI ES NECESARIO. EN OTROS CASOS, SE TRATARÁ LA ENFERMEDAD O AFECCIÓN SUBYACENTE RESPONSABLE DE LA ACANTOSIS NIGRICANS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 32,
        diagnosis: "ONICOMICOSIS (SEGUNDA ENTRADA)",
        diagnosis_short: "Onicomicosis (con educación ampliada)",
        triage_seed: "YELLOW",
        tags: ["onicomicosis", "uñas", "hongos", "terbinafina", "dermatofitos", "trichophyton rubrum", "calzado"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: ONICOMICOSIS",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- TERBINAFINA 250MG AL DÍA X 12 SEMANAS (EVALUAR QUE EL PACIENTE NO ESTÉ TOMANDO ESTATINAS O FIBRATOS O QUE TENGA OTRA CONTRAINDICACIÓN PARA SU USO) (MEDICAMENTO DE CANASTA). SI PACIENTE TIENE POLIFARMACIA HACER CONTROL DE PERFIL HEPÁTICO, HEMOGRAMA Y FUNCIÓN RENAL AL MES Y A LOS 3 MESES. 2.- CONTROL X TELEDERMATOLOGIA EN 3 MESES CON ESTAS Y NUEVAS FOTOS.",
        education_text: "EXPLICAR QUE EN LAS ONICOMICOSIS SE PUEDE PLANTEAR UN TRATAMIENTO EMPÍRICO, CONSIDERANDO QUE EL 90% DE LOS CASOS SON POR DERMATOFITOS, CUYA MAYOR ETIOLOGÍA ES EL T. RUBRUM. EL TRATAMIENTO SIEMPRE DEBE SER ORAL PARA UNA ADECUADA RESPUESTA. EN FORMA COMPLEMENTARIA SE DEBE ACONSEJAR AL PACIENTE: USO DE CALZADOS RESPIRABLES O EL MENOR TIEMPO POSIBLE DE CALZADOS MUY OCLUSIVOS. USO DE CALCETINES DE ALGODÓN, USO DE ALGÚN TALCO ANTIMICÓTICO EN EL CALZADO. FRECUENTE CORTE DE UÑAS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 33,
        diagnosis: "ONICOMICOSIS DISTAL",
        diagnosis_short: "Onicomicosis distal",
        triage_seed: "YELLOW",
        tags: ["onicomicosis", "distal", "uñas", "hongos", "laca ungueal", "topico", "dermatofitos"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: ONICOMICOSIS DISTAL",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: TERAPIA TÓPICA (NO DISPONIBLES EN CANASTA) COMO POR EJ. PRIVEX LACA UNGUEAL, APLICAR EN LAS NOCHES EN UÑAS AFECTADAS HASTA MEJORAR (POR LO MENOS 6 MESES).",
        education_text: "EXPLICAR QUE EN LAS ONICOMICOSIS SE PUEDE PLANTEAR UN TRATAMIENTO EMPÍRICO, CONSIDERANDO QUE EL 90% DE LOS CASOS SON POR DERMATOFITOS, CUYA MAYOR ETIOLOGÍA ES EL T. RUBRUM. EL TRATAMIENTO SIEMPRE DEBE SER ORAL PARA UNA ADECUADA RESPUESTA. SE DEBE ACONSEJAR: USO DE CALZADOS RESPIRABLES, CALCETINES DE ALGODÓN, TALCO ANTIMICÓTICO EN EL CALZADO Y FRECUENTE CORTE DE UÑAS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 34,
        diagnosis: "FITODERMATOSIS",
        diagnosis_short: "Fitodermatosis",
        triage_seed: "GREEN",
        tags: ["fitodermatosis", "plantas", "fitofotodermatitis", "contacto", "clobetasol", "fotoproteccion", "alergia"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: FITODERMATOSIS",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- MEDIDAS GENERALES: EVITAR EXPOSICIÓN AL SOL Y A CONTACTO CON PLANTAS COMO MALEZAS, LITRE, ORTIGAS, ETC. 2.- CLOBETASOL CREMA 0,05% APLICAR 2 VECES AL DÍA X 7 DÍAS EN LESIONES, LUEGO 1 VEZ AL DÍA X 7 DÍAS Y DESCANSAR 14 DÍAS, REPETIR 2 CICLOS (MEDICAMENTO CANASTA). 3.- LUBRICAR CON CREMA HUMECTANTE (MEDICAMENTO CANASTA) O NIVEA TAPA AZUL, LUBRIDERM, PIELARMINA O VASELINA SÓLIDA VARIAS VECES AL DÍA. 4.- HIDROXICINA 20MG 1 COMPRIMIDO EN LA NOCHE X 1 MES, SI NO TIENEN USAR CLORFENAMINA (MEDICAMENTO CANASTA). 5.- CONTROL POR TELEDERMATOLOGIA 1 MES O SOS.",
        education_text: "EXPLICAR QUE ES ESENCIAL EVITAR LA EXPOSICIÓN A SUSTANCIAS FITOFOTODERMATOGÉNICAS SEGUIDA DE EXPOSICIÓN AL SOL. ESTO PUEDE INCLUIR LAVARSE BIEN LAS MANOS Y OTRAS ÁREAS DE LA PIEL DESPUÉS DE MANIPULAR CIERTAS PLANTAS O FRUTAS. EL USO DE PROTECTOR SOLAR PUEDE AYUDAR A PREVENIR LA REACCIÓN SI SE ESPERA ESTAR EXPUESTO AL SOL DESPUÉS DE ENTRAR EN CONTACTO CON SUSTANCIAS DESENCADENANTES. LA PREVENCIÓN, MEDIANTE LA IDENTIFICACIÓN Y EVITACIÓN DE LAS SUSTANCIAS DESENCADENANTES, ES CLAVE.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 35,
        diagnosis: "FOLICULITIS DE LA NUCA O ACNE QUELOIDEO",
        diagnosis_short: "Foliculitis de la nuca / Acné queloideo",
        triage_seed: "RED",
        tags: ["foliculitis", "nuca", "acne queloideo", "queloides", "derivar", "especialista", "doxiciclina", "isotretinoina"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: FOLICULITIS DE LA NUCA O ACNÉ QUELOIDEO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: DEBE SER DERIVADO A DERMATOLOGÍA PUESTO QUE ES UNA PATOLOGÍA DE MANEJO POR ESPECIALIDAD DEBIDO A LA COMPLEJIDAD DE SU TRATAMIENTO. MIENTRAS ESPERA INICIAR: 1.- DOXICICLINA 100MG 1 COMPRIMIDO CADA 12 HRS POR 14 DÍAS Y LUEGO 1 COMP AL DÍA POR 3 MESES (LUEGO DE ALMORZAR O CENAR). DESCARTAR ALERGIAS A TETRACICLINAS. 2.- KETOCONAZOL 2% SHAMPOO USAR 4 VECES POR SEMANA DEJANDO LA ESPUMA 5 MIN POR 3 MESES. 3.- XINDER O CLOBX SHAMPOO USO 3 VECES POR SEMANA. 4.- SOLICITAR EXÁMENES PARA MANEJO EN NIVEL SECUNDARIO: HEMOGRAMA VHS, PERFIL HEPÁTICO, PERFIL LIPÍDICO, CREATININA PARA EVENTUAL INICIO DE ISOTRETINOÍNA ORAL.",
        education_text: "EXPLICAR QUE EL MANEJO MÉDICO TRADICIONAL SE ENFOCA EN LA PREVENCIÓN, EL USO DE ANTIBIÓTICO TÓPICO U ORAL Y ESTEROIDES INTRALESIONALES PARA DISMINUIR LA INFLAMACIÓN Y LA INFECCIÓN SECUNDARIA. EL TRATAMIENTO MÉDICO REQUIERE MESES PARA ALCANZAR RESULTADOS Y SON FRECUENTES LAS RECURRENCIAS. EL MANEJO QUIRÚRGICO ES INVASIVO Y REQUIERE MAYOR TIEMPO PARA LA RECUPERACIÓN. LA CRIOTERAPIA, EL DIÓXIDO DE CARBONO Y LA ABLACIÓN CON LÁSER SON ALTERNATIVAS CON RESULTADOS LIMITADOS.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 36,
        diagnosis: "VERRUGA COMUN",
        diagnosis_short: "Verruga común",
        triage_seed: "GREEN",
        tags: ["verruga", "comun", "acido salicilico", "acido lactico", "vitamina c", "HPV", "crioterapia"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: VERRUGA COMÚN",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- SUPLEMENTAR CON VITAMINA C 1 GR AL DÍA POR 3 MESES O THUJA D6 1 COMPRIMIDO CADA 8 HRS POR 2 MESES. 2.- FORMULAR RECETA: ÁCIDO SALICÍLICO 16% + ÁCIDO LÁCTICO 16% EN COLODIÓN FLEXIBLE CSP: 15 ML. APLICAR EN LAS NOCHES EN LA VERRUGA EVITANDO EL CONTACTO CON LA PIEL SANA, PROTEGIENDO LA PIEL SANA DE LA PERIFERIA CON PASTA LASSAR O VASELINA Y LUEGO CUBRIR CON MICROPORE. REALIZAR TRATAMIENTO POR 2–3 MESES. ANTES DE APLICAR EL LÍQUIDO, PUEDE RASPARSE LA VERRUGA CON LIMA DE CARTÓN O PIEDRA PÓMEZ. 3.- SI LA VERRUGA PERSISTE DESPUÉS DE 3 MESES, VERIFICAR ADHERENCIA AL TRATAMIENTO. SI ESTÁ BIEN REALIZADO, DERIVAR A DERMATOLOGÍA PARA CRIOTERAPIA U OTRAS ALTERNATIVAS.",
        education_text: "EXPLICAR QUE DEBE TENER UNA BUENA HIDRATACIÓN DE MANOS Y EVITAR EL GRATAJE.",
        source: "PROTOCOLOS TD 2023"
    },
    {
        id: 37,
        diagnosis: "HERPES ZOSTER",
        diagnosis_short: "Herpes Zóster",
        triage_seed: "GREEN",
        tags: ["herpes", "zoster", "vesiculas", "ampollas", "dolor", "dermatomal", "valaciclovir", "aciclovir"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: HERPES ZÓSTER",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- ACICLOVIR 800 MG 5 VECES AL DÍA POR 7 DÍAS O VALACICLOVIR 1 GR CADA 8 HORAS POR 7 DÍAS (INICIAR IDEALMENTE ANTES DE LAS 72 HRS). 2.- MANEJO DEL DOLOR CON PARACETAMOL 1 GR CADA 8 HRS O AINES SEGÚN TOLERANCIA. SI HAY DOLOR NEUROPÁTICO, CONSIDERAR PREGABALINA O GABAPENTINA. 3.- FOMENTOS CONDICIÓN CON SUERO FISIOLÓGICO Y SECADO CUIDADOSO. 4.- DERIVAR A OFTALMOLOGÍA URGENTE SI ESTÁ COMPROMETIDA LA RAMA OFTÁLMICA DEL NERVIO TRIGÉMINO (PUNTA DE LA NARIZ).",
        education_text: "EXPLICAR QUE ES UNA REACTIVACIÓN DEL VIRUS DE LA VARICELA. OCURRE TÍPICAMENTE EN UN SOLO LADO DEL CUERPO Y PUEDE SER MUY DOLOROSO. DEBE EVITAR CONTACTO CON EMBARAZADAS Y PERSONAS INMUNOSUPRIMIDAS QUE NO HAYAN TENIDO VARICELA MIENTRAS HAYA VESÍCULAS. EL DOLOR PUEDE DURAR SEMANAS DESPUÉS DE MEJORAR LA PIEL.",
        source: "Guía Clínica MINSAL"
    },
    {
        id: 38,
        diagnosis: "URTICARIA AGUDA",
        diagnosis_short: "Urticaria aguda",
        triage_seed: "GREEN",
        tags: ["urticaria", "aguda", "ronchas", "habones", "prurito", "alergia", "antihistaminicos", "cetirizina", "loratadina"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: URTICARIA AGUDA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- ANTIHISTAMÍNICOS DE SEGUNDA GENERACIÓN (CETIRIZINA, LORATADINA, LEVOCETIRIZINA, RUPATADINA) 1 COMPRIMIDO AL DÍA, PUDIENDO AUMENTAR HASTA 4 VECES LA DOSIS SEGÚN RESPUESTA. 2.- EN CASO DE ANGIOEDEMA SEVERO O COMPROMISO RESPIRATORIO, DERIVAR A SERVICIO DE URGENCIA PARA MANEJO CON EPINEFRINA / CORTICOIDES SISTÉMICOS. 3.- IDENTIFICAR Y EVITAR EL POSIBLE GATILLANTE (FÁRMACOS, INFECCIONES, ALIMENTOS).",
        education_text: "LA URTICARIA SE CARACTERIZA POR RONCHAS ROJAS Y PRURIGINOSAS QUE APARECEN Y DESAPARECEN EN MENOS DE 24 HORAS EN EL MISMO LUGAR. EN LA MAYORÍA DE LOS CASOS DE URTICARIA AGUDA, SE RESUELVE SOLA EN POCOS DÍAS O SEMANAS. ACUDIR INMEDIATAMENTE A URGENCIA SI SIENTE DIFICULTAD PARA RESPIRAR O HINCHAZÓN DE CARA/LABIOS/LENGUA.",
        source: "Guía Clínica MINSAL"
    },
    {
        id: 39,
        diagnosis: "IMPETIGO",
        diagnosis_short: "Impétigo",
        triage_seed: "GREEN",
        tags: ["impetigo", "costras", "mielicericas", "infeccion", "bacteriana", "pediatrico", "mupirocina", "cloxacilina"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: IMPÉTIGO",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- ASEO DE LAS LESIONES CON AGUA Y JABÓN, RETIRANDO SUAVEMENTE LAS COSTRAS. 2.- PARA ENFERMEDAD LOCALIZADA (POCAS LESIONES): MUPIROCINA 2% UNGÜENTO O CREMA, 2 VECES AL DÍA POR 5 A 7 DÍAS. 3.- PARA ENFERMEDAD EXTENSA O MÚLTIPLES LESIONES: FLUCLOXACILINA (CLOXACILINA) ORAL POR 7 DÍAS. EN ALÉRGICOS A PENICILINA USAR CEFADROXILO O MACRÓLIDOS. 4.- CONTROL EN APS SI NO HAY MEJORÍA EN 48-72 HORAS.",
        education_text: "ES UNA INFECCIÓN BACTERIANA MUY CONTAGIOSA, MÁS FRECUENTE EN NIÑOS. SE CARACTERIZA POR COSTRAS DE COLOR MIEL. SE DEBE MANTENER ESTRICTA HIGIENE, LAVADO DE MANOS FRECUENTE Y NO COMPARTIR TOALLAS O ROPA. LOS NIÑOS NO DEBEN ASISTIR AL COLEGIO HASTA LLEVAR 24 HORAS DE TRATAMIENTO ANTIBIÓTICO.",
        source: "Guía Clínica MINSAL"
    },
    {
        id: 40,
        diagnosis: "PITIRIASIS ROSADA",
        diagnosis_short: "Pitiriasis Rosada",
        triage_seed: "GREEN",
        tags: ["pitiriasis", "rosada", "medallon", "heraldo", "descamacion", "prurito", "arbol", "navidad", "tronco"],
        diagnostic_suggestion_text: "DADO LOS ANTECEDENTES ENTREGADOS Y LAS FOTOGRAFIAS PRESENTADAS, LA ORIENTACION DIAGNOSTICA ES: PITIRIASIS ROSADA",
        management_text: "DADO LO ANTERIOR, LA SUGERENCIA DE MANEJO ES: 1.- ENFERMEDAD AUTOLIMITADA (RESUELVE EN 6-8 SEMANAS NORMALMENTE). SE REQUIERE MANEJO REASEGURADOR. 2.- PARA EL PRURITO: ANTIHISTAMÍNICOS ORALES (CETIRIZINA O LORATADINA) O HIDROXICINA EN LA NOCHE SI ALTERA EL SUEÑO. 3.- LUBRICACIÓN DE LA PIEL (VASELINA, CREMAS NEUTRAS). 4.- CORTICOIDES TÓPICOS DE MEDIANA POTENCIA (EJ. BETAMETASONA 0.05%) SOLO EN LESIONES MUY SINTOMÁTICAS O QUE PIQUEN MUCHO, POR CURSOS CORTOS (7-10 DÍAS).",
        education_text: "ES UNA ERUPCIÓN BENIGNA Y AUTOLIMITADA QUE SUELE EMPEZAR CON UNA PLACA MÁS GRANDE (\"MEDALLÓN HERALDO\") SEGUIDA DE MUCHAS MÁS PEQUEÑAS EN EL TRONCO. SUELE PENSARSE QUE ESTÁ RELACIONADA CON UNA INFECCIÓN VIRAL PREVIA. NO ES PELIGROSA, PERO PUEDE TARDAR HASTA 2-3 MESES EN DESAPARECER COMPLETAMENTE.",
        source: "Guía Clínica MINSAL"
    }
];